user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzE1NDc=

session:
  key: NomFgE3-_XPGZWsXv1rE4LAmZb3hqo19zwMkmFlrQsA=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk1.a.rpc36ZAamg4GbJ8tgrc0KC41lwJ2Rv79AdykzLt_GlPclIhu5i-61AhQQRzqRLY9Ng4yErt-MyRUZ5r8381AloFJkV-_ulQSLUo3OOu90OefSNusuxV3MjyWUgSEv0okuvaBZRTrHCh_bkh1s1luZRVnTlQXXjTMGA6gYlb1uvrluR4XSfsZf1DcRKEhQhcx
  group_id: 215461654
